### ISSUE TITLE
documentation skool2asm.py shows --hex instead of --skoolhex

### ISSUE THREAD

**Issue by stefandrissen** [skoolkid/skoolkit#101]
http://skoolkit.ca/docs/skoolkit/commands.html

skool2asm.py

  -H, --hex             Write the disassembly in hexadecimal.

The long parameter should be

--skool-hex

**Comment by skoolkid** [comment]
The long option for skool2asm.py is definitely --hex, not --skool-hex.

Are you thinking of sna2skool.py -H/--skool-hex?

**Comment by stefandrissen** [comment]
Sorry - you are completely correct - I jumped from the quick DIY -H to the commands and got lost... I was indeed attempting to enrich my sna2skool and somehow ended up looking at skool2asm instead :-)
