### ISSUE TITLE
Top of file comments

### ISSUE THREAD

**Issue by mrcook** [skoolkid/skoolkit#103]
Would it be possible to maintain top-of-file comments during conversion?

The specific case I'm thinking about is in regard to release information. For example, in your Skooldaze [sd.skool](https://github.com/skoolkid/skooldaze/blob/master/sources/sd.skool) you have this comment;
```
; Copyright 2008-2015, 2017, 2018 Richard Dymond
```

But if I generate a new control file with `skool2ctl.py`, this comment is lost. As it does when adding that comment to the `.ctl` file and then running `sna2skool.py`.

I think it is important to maintain this kind of information during conversion.

Thanks!

**Comment by skoolkid** [comment]
Preserving 'dangling' comment blocks (i.e. ones that are not attached to an entry) in a control file has been on my TODO list for a while. I'll bring it into scope for SkoolKit 7.0 and give it some thought.

**Comment by mrcook** [comment]
Thanks for considering the request Richard.

**Comment by skoolkid** [comment]
A dangling comment block can now be marked for preservation by skool2asm.py and skool2ctl.py (and other commands) by using the `@retain` directive.

https://skoolkit.readthedocs.io/en/latest/asm.html#retain

**Comment by mrcook** [comment]
Thanks Richard, this works quite well.

One thing I discovered was the need for a blank line after the retained comment block in the `.skool`, otherwise it made a real mess when converting to the `ctl` file. If this is expected then it might be worth emphasising that in the docs.

**Comment by mrcook** [comment]
The comments at the top of my current [skool file](https://github.com/mrcook/chuckie-egg-disassembly/blob/master/chuckie-egg.skool) are not being retained when converting to ASM.

This is the command I run: `skool2asm.py -H -c chuckie-egg.skool > chuckie-egg.asm`

Although I do get a few warnings on the conversion, it doesn't seem like they should be related to this problem.

**Comment by skoolkid** [comment]
The comment block at the top of your skool file is not retained when converting to ASM because the `@start` directive doesn't appear until later on. If you move the `@start` directive up, it should work.

By the way, I'm now considering making the `@retain` directive unnecessary by just preserving dangling comment blocks by default. I'll keep you posted!

**Comment by skoolkid** [comment]
And `@retain` is gone: 19cd1beb0610e5626d6e06365153146cc36b9ab9.

All dangling comment blocks are now reproduced by skoolasm.py and preserved by skool2ctl.py.
