### ISSUE TITLE
Unknown block type (2) in header block

### ISSUE THREAD

**Issue by al-arz** [skoolkid/skoolkit#104]
More of a question than an issue since I'm just starting to get into disassembly. Why does tap2sna throw an error when it encounters header blocks with type 1 or 2, which are valid blocks?

**Comment by skoolkid** [comment]
That's because tap2sna.py doesn't know what to do with a number array (type 1) or a character array (type 2): it can only work with programs (type 0) and bytes (type 3).

What is the tape that you're trying to convert?

**Comment by al-arz** [comment]
And can't some kind of "load as-is" be an option? Sorry if I'm asking dumb things.

The tape is Rebelstar Raiders: http://www.worldofspectrum.org/infoseekid.cgi?id=0004064

**Comment by skoolkid** [comment]
The reason tap2sna.py cannot handle number arrays and character arrays automatically is that it does not know where to load them. They do not have an obvious start address like Program blocks and Bytes blocks.

If you know where a data block should be loaded, you can provide tap2sna.py with the start address by using '--ram load'. For example:

    $ tap2sna.py --ram load=2,30000 game.tap game.z80

would load the second block on the tape at address 30000.

By the way, Rebelstar Raiders side 1 is pretty complex - it has 30 blocks. Unless you can figure out where each data block should be loaded and have the patience to provide that info to tap2sna.py, you'd be better off loading the tape in an emulator and saving a snapshot when it's finished.

**Comment by al-arz** [comment]
Thank you for tips and clarification! I'll follow your recommendation then.
