### ISSUE TITLE
Ignore a branch/subroutine

### ISSUE THREAD

**Issue by ZXGuesser** [skoolkid/skoolkit#106]
Is there a way to indicate in a control file that a jump/call should be ignored entirely? That is, not go down that branch at all when generating the skool file.
The code in question is part of a relocated routine which pages out the ROM I'm disassembling and calls into the system ROM. Skoolkit creates confusing labels and references at those locations in the ROM code.

**Comment by skoolkid** [comment]
If you want to prevent the operand of a JP/CALL instruction from being converted to a label or being hyperlinked in the HTML output, you can use the [@keep](http://skoolkid.github.io/skoolkit/asm.html#keep) directive. Have you tried that?

**Comment by skoolkid** [comment]
Ah, yes, in 7.0 a blank `@label` will remove an entry point marker, and *sna2skool.py* processes `@label` directives while reading a control file. Glad to hear it paid to upgrade!

**Comment by ZXGuesser** [comment]
I've just generated my disassembly in version 8.1 and I have a similar issue again. It's adding a "used by the routines at" message to my first system variable because two routines copy a stub of code to that location (the printer buffer) and jump to it. Is there some way to suppress that?

**Comment by skoolkid** [comment]
Does `@label=` no longer work as it did before, or do you want a label defined now while also suppressing the "used by" comment?

In any case, defining a description for the system variable (with a `D` directive) will suppress the "used by" comment (so long as you're not forcing "used by" comments with `ListRefs=2`).

**Comment by ZXGuesser** [comment]
Yeah to have a label but not the used by in this case. Having looked I am forcing ListRefs=2 in my ini file, doh. I can't now remember why I needed to do that!

**Comment by skoolkid** [comment]
I might look into enhancing the [@refs](https://skoolkit.readthedocs.io/en/latest/asm.html#refs) directive (which will be new in 8.2) so that it can specify referrers to remove as well as add. That would enable you to suppress the "used by" comments even with `ListRefs=2`.

**Comment by skoolkid** [comment]
Made the enhancement to the `@refs` directive in 212af0e71c4587f8e4c30be065d71f860e9580af. It will be in 8.2 (due for release some time this month).
