### ISSUE TITLE
Recreated .tap file crashes emulated ZX Spectrum

### ISSUE THREAD

**Issue by chupocro** [skoolkid/skoolkit#109]
I've been following the Hungry Horace example and the resulting **.tap** file crashes the emulated ZX Spectrum. This is what I have done starting with **hungry_horace.z80** snapshot:

```
python sna2skool.py -c examples/hungry_horace.ctl hungry_horace.z80 > horace.skool
python skool2asm.py horace.skool > horace.asm 2> warnings.txt
sjasmplus.exe horace.asm
python bin2tap.py horace.bin
```

There are many warnings when running **skool2asm.py**, that's why I redirected **stderr** to the file **warnings.txt** so you can see them.

This is how I edited the **.asm** before running **sjasmplus**:

```
device zxspectrum48
...
...
savebin "horace.bin", 24576, 32639+8-24576
```

I am getting the same result using **pasmo**. I tried to convert the **.tap** file to the snapshot using **tap2sna.py** but it crashes Spectrum too. Seems as the **.tap** file is somehow overwriting system vars and/or Basic.

Here you are all the files and the warnings.
[hungry_horace.zip](https://github.com/skoolkid/skoolkit/files/4692317/hungry_horace.zip)

**Comment by skoolkid** [comment]
Because `horace.bin` doesn't extend all the way to 65535, you need to specify the origin address (24576) when creating the TAP file. Try this:

    python bin2tap.py -o 24576 horace.bin

**Comment by chupocro** [comment]
That's it, thank you very much! So one way to extend the **.bin** file to #FFFF using **sjasmplus** is to edit the **.asm** file like this:

```
            org 24576
            OUTPUT horace.bin    ; no need for device = zxspectrum48

            ; The game has just loaded
progstart   DI
            LD A,(23672)
            LD L,A
            ; ...
            ; ...
            DEFB 15,7,7,5,0,0,0,0
            DEFB 0,0,0,128,128,0,0,0
progend

            fpos #FFFF - progstart
            org #FFFF
romend      byte #c9  ; can be any byte

            display " "
            display "ERRORS        : ", /d, _ERRORS
            display "WARNINGS      : ", /d, _WARNINGS
            display "PROGRAM LENGTH: ", /a, progend - progstart, " bytes"
            display "ROM LENGTH    : ", /a, romend + 1 - progstart, " bytes"
            display " "
```

Now, the **bin2tap** can be called without specifying **-o** parameter because the last byte of **.bin** will be 65535. However, the OUTPUT directive for some reason doesn't work with the most recent version of **sjasmplus** so I had to use some old version I was using for generating ROMs for Pac-Man hardware.

BTW, I find the install instructions for SkoolKit slightly confusing. Here is what took me some time when I tried to follow the Hungry Horace example to see how everything works:

Since it was mentioned the SkoolKit could be installed through PIP, that was how I've installed it. The first steps in the Hungry Horace example were to use **tap2sna.py** and **sna2skool.py** and since the only **.py** programs with those names were inside Python's **site-packages\skoolkit** folder I copied those scripts into the working directory but only later I realized there are .py scripts with the same name inside skoolkit-8.1.zip archive and those are the files which call the programs from the **site-packages\skoolkit** and which I must use.

I think a sentence or two about that in "Getting started" and/or "Installing and using SkoolKit" would be of a great help to someone who would be trying to use SkoolKit for the first time.

And one more thing - it seems to me SkoolKit could be used for disassembling some arcade machines which have one or more Z80 processors too, for example Scramble.

**Comment by skoolkid** [comment]
Regarding SkoolKit installation, if you used pip, then SkoolKit's command scripts should have been installed in C:\Python3X\Scripts. If they weren't for some reason, you could try installing SkoolKit using setup.py in the zip archive. See [here](https://skoolkid.github.io/skoolkit/usage.html#windows) for instructions.

**Comment by chupocro** [comment]
Yes, the command scripts were installed in c:\Python38-32\ZX_ENV\Scripts (I am using virtualenv) and the Script foder is added to path when activating the virtual environment but I didn't configure shebang support so .py scripts must be called by **python name.py** where the name of the script is a parameter so the script has to be in the same folder to avoid typing the path to the script. I did read the instructions but when I was copying the scripts I copied the wrong ones.

I generated the .asm using **--create-labels** to see how much work will be still left to produce a relocatable listing where you could insert instructions anywhere without breaking the hard coded addresses. Are there any disassemblies made to be relocatable? Is there a forum dedicated to SkoolKit?

BTW, I installed SkoolKit in a virtual Windows 7 machine on Windows 10 host because I didn't want Python 3 installation to break Python 2. I know there is Python launcher but I used the virtual machine anyway.

**Comment by skoolkid** [comment]
I made some effort to make the first two disassemblies I ever worked on (Skool Daze and Back to Skool, downloadable [here](https://skoolkit.ca/disassemblies/)) relocatable, by adding `@rsub` directives to the skool files. They seemed to work the last time I checked, but it's hard to verify that they work exactly like the original code.

There's no forum dedicated to SkoolKit, but sometimes users of the [Spectrum Computing Forums](https://spectrumcomputing.co.uk/forums/) and the [World of Spectrum Forums](https://worldofspectrum.org/forums/) ask questions about SkoolKit - and I even answer them if I notice them!

**Comment by chupocro** [comment]
I remember seeing your Skool Daze disassembly many years ago but I don't remember anything about SkoolKit, maybe it was before you released the tool or before you named it.

There are (too) many interesting games and routines to disassemble but unfortunately one person couldn't reverse engineer all that code even in a 100 years. It takes quite a while even when I try to understand old commented asm code that I wrote, not to speak of deciphering the code generated by disassembler.
