### ISSUE TITLE
Character 94 (↑) breaks HTML file writing on Windows

### ISSUE THREAD

**Issue by Wolfe-Lyon** [skoolkid/skoolkit#110]
The default encoding used by Python to write (text) files on Windows (8.1) is not UTF-8. As a result, attempts to write the "↑" character to an output file causes an exception to be raised. Running the attached [skool file](https://github.com/skoolkid/skoolkit/files/4909624/skool_file.txt) through skool2html generates the following output on Windows:

> Found no ref file for unicode.skool
Parsing unicode.skool
Output directory: unicode
Writing disassembly files in asm
Traceback (most recent call last):
  File "skool2html.py", line 24, in \<module\>
    skool2html.main(sys.argv[1:])
  File "skoolkit\skool2html.py", line 401, in main
    run(namespace.infiles, namespace)
  File "skoolkit\skool2html.py", line 228, in run
    write_disassembly(html_writer, options.files, ref_search_dir, options.search, pages, options.themes, options.single_css)
  File "skoolkit\skool2html.py", line 265, in write_disassembly
    clock(html_writer.write_asm_entries, message)
  File "skoolkit\skool2html.py", line 81, in clock
    result = operation(*args, **kwargs)
  File "skoolkit\skoolhtml.py", line 756, in write_asm_entries
    self.write_entries(self.code_path, self.paths['MemoryMap'])
  File "skoolkit\skoolhtml.py", line 753, in write_entries
    self.write_entry(cwd, i, map_file)
  File "skoolkit\skoolhtml.py", line 739, in write_entry
    self.write_file(fname, html)
  File "skoolkit\skoolhtml.py", line 819, in write_file
    f.write(contents)
  File "...\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2191' in position 821: character maps to \<undefined\>

Running on Ubuntu (14.04.6 LTS) works as expected.

Attempts to pipe the output of snapinfo.py -b [snapshot] to a file on Windows raises a similar exception when the basic listing contained within the snapshot includes the "↑" character.

Should skoolkit explicitly open text files for writing with UTF-8 encoding rather than rely on the default for a given platform?

**Comment by skoolkid** [comment]
If you first run the command

    set PYTHONIOENCODING=utf8

does it fix the problem?

**Comment by Wolfe-Lyon** [comment]
> 
> 
> If you first run the command
> 
> ```
> set PYTHONIOENCODING=utf8
> ```
> 
> does it fix the problem?

No. I have tried several variants:

- utf8
- UTF8
- utf-8
- UTF-8

None of these worked.

**Comment by skoolkid** [comment]
Looks as if that environment variable only affects stdin/stdout/stderr.

Could you try this instead?

    set PYTHONUTF8=1

Note that this will only work (if at all) with Python 3.7+.

**Comment by Wolfe-Lyon** [comment]
> 
> 
> Looks as if that environment variable only affects stdin/stdout/stderr.
> 
> Could you try this instead?
> 
> ```
> set PYTHONUTF8=1
> ```
> 
> Note that this will only work (if at all) with Python 3.7+.

I'm using Python 3.7.4 and this works.

It looks like skoolkit may need to be explicit about which encoding to use when writing files.

**Comment by skoolkid** [comment]
As of e97f870a278658ae1af18e724bbe04dfb2c02f49, skool2html.py will use UTF-8 when writing HTML files.

That won't fix the issue with directing the output of snapinfo.py (for example) to a file. You'll still need to set the environment variable `PYTHONIOENCODING` to fix that.

**Comment by Wolfe-Lyon** [comment]
I can confirm it now works without the environment variable being set. Thanks!

**Comment by Wolfe-Lyon** [comment]
Unfortunately the same issue affects:

- skool2ctl (when the skool file contains ↑)
- sna2skool (when the ctl file contains ↑)
- likely other skoolkit commands that I haven't tested
