### ISSUE TITLE
"got an unexpected keyword argument" when nesting macro(s) inside #CALL

### ISSUE THREAD

**Issue by Wolfe-Lyon** [skoolkid/skoolkit#113]
When nesting a macro that evaluates to a string containing the '=' character inside a #CALL method, an exception is raised. For example, when using the following:

`#CALL:do_something(#R54321)`

this exception is raised:

`ERROR: Error while parsing #CALL macro: Method call do_something(#R54321) failed: do_something() got an unexpected keyword argument '<a href'`

It seems that the argument parsing code is detecting keyword arguments because of the '=' character(s) in the output of the #R macro.

Is there a mechanism to escape the '=' characters?

It would also be very useful to escape commas too, for example to pass the string 'LD A,B' to a #CALL method as a single argument. Is this currently possible?

**Comment by skoolkid** [comment]
No, there's no way to escape equals signs or commas in the arguments of a `#CALL` macro. You should consider implementing a custom macro (with an `expand_macroname` method) instead.

Just out of interest, why are you passing an `#R` macro as an argument to a `#CALL` macro? Perhaps I could suggest an alternative to implementing a custom macro if I knew what you're trying to achieve.

**Comment by Wolfe-Lyon** [comment]
Thanks. My intention was to write a #CALL method that would take an
instruction as its argument and wrap it in a <span> tag in order that a CSS
style could be applied to it. This would work in a similar way to the #REG
macro, but allowing the style to differ from that offered by #REG.

Essentially I wanted to make instructions in annotations stand out from the
surrounding text, but preserving the hyperlinks in, for example, JP
instructions, hence the requirement that #R is accepted as an argument.

**Comment by skoolkid** [comment]
Ah, I see. In that case you should be able to define a custom macro using `#DEFINE`, something like this:

    #DEFINE0,1(INSTR,<span class="instruction">{}</span>)

Then you could write:

    #INSTR/LD A,(#R30000)/

to style an instruction that includes a hyperlink.

Let me know if that works for you.

**Comment by Wolfe-Lyon** [comment]
That worked very well. Thank you!
