### ISSUE TITLE
Document the usage of bugfix directives in control files

### ISSUE THREAD

**Issue by morozov** [skoolkid/skoolkit#114]
I'm trying to replace the operand in a `JR NZ` instruction using `@ofix` which is documented as: https://github.com/skoolkid/skoolkit/blob/6e433a3c52078a9b6f5965c30918c28f9b06e66d/sphinx/source/asm.rst#L105-L111

I'm using a control file to build the skool file. The usage bugfix directives in control files is documented as: https://github.com/skoolkid/skoolkit/blob/2fb642ec6dea590a9ff5d3048bb4593840958d22/sphinx/source/control-files.rst#L684-L696

It's not really how to replace code, not a comment from a control file. I couldn't find any projects that would do that. Would it be possible to document how the example from `asm.rst` could be described in a control file? Are there existing projects that implement such logic that could be used as a reference?

**Comment by skoolkid** [comment]
I'm not quite sure what you're asking. The `@*fix` directives all use the same syntax, which is documented under [@bfix](https://skoolkit.ca/docs/skoolkit/asm.html#bfix). So to change the operand of a `JR NZ` instruction with an `@ofix` directive you'd do something like this in the skool file:

    @ofix=JR NZ,$8001
     $8002 JR NZ,8000

which translates to this in the control file:

    @ $8002 ofix=JR NZ,$8001

**Comment by morozov** [comment]
This is what I was looking for. Thank you. Sorry, I had only noticed the syntax with begin/end/else.
