### ISSUE TITLE
Issues when instructions overrun the end of RAM

### ISSUE THREAD

**Issue by Wolfe-Lyon** [skoolkid/skoolkit#116]
In Spellbound, Knight Tyme and Stormbringer there is an instruction that overruns the end of RAM:

`65535 JR 65524`

A skool file with such a terminal instruction is causing two issues that I am aware of.

### Issue 1

Converting the skool file to a control file with skool2ctl, and then using this control file to regenerate the skool file with sna2skool results in the instruction above being replaced with:
`65535 DEFB 24`

It would be good if, with the appropriate directive `@defb=0:243` in the skool file, this terminal instruction could be preserved when the above process is carried out.

### Issue 2

Converting the skool file to a bin file with skool2bin, and then using this bin file to create a snapshot with bin2sna results in a snapshot with at least some of its contents offset by one byte with respect to the skool file that was used to create it. The skool2bin command gives the following output:

_Wrote original.bin: start=23296, end=65537, size=42241_

 Replacing the terminal instruction in the skool file with `DEFB 24` and running this version through skool2bin and then bin2sna results in a 'correct' snapshot as expected. The output from skool2bin in this case is:

_Wrote modified.bin: start=23296, end=65536, size=42240_

**Comment by skoolkid** [comment]
Regarding issue 2, my guess is that you need to specify the origin address (via the `--org` option) when using `bin2sna.py`. If you give `bin2sna.py` a 42241-byte file, it will assume by default that the origin address is 23295 (=65536-42241), which would lead to the off-by-one issue you're seeing.

**Comment by Wolfe-Lyon** [comment]
> 
> 
> Regarding issue 2, my guess is that you need to specify the origin address (via the `--org` option) when using `bin2sna.py`. If you give `bin2sna.py` a 42241-byte file, it will assume by default that the origin address is 23295 (=65536-42241), which would lead to the off-by-one issue you're seeing.

The issue is that the byte at 65536 (0) is being appended to the end of the binary file, pushing everything else down by one byte. I eventually got around it by passing `--end 65536` to `skool2bin.py`. Is `skool2bin.py` meant to convert content at addresses higher than 65535?

**Comment by skoolkid** [comment]
I think it makes sense for `skool2bin.py` to convert whatever it's given, even if that means crossing the 64K boundary. As you've discovered, if you don't want the extra bytes in the binary file, you can use `--end 65536` to omit them.

As for issue 1, with 24094ab37564911f55a32809f70a2d76891f4846 in place, I just need to add a configuration parameter to `sna2skool.py` for enabling disassembly of an instruction that crosses the 64K boundary. By default, that feature will be disabled.

**Comment by skoolkid** [comment]
With b9b58830aa4f5448b931e567585e03b3bafc373d in place, you can now restore an instruction that wraps around the 64K boundary from a control file. For example, starting with this skool file (let's call it *wrap.skool*):

    @defb=0:254
    ; Jump at the boundary
    c65535 JR 65535

you can do the following round trip to get back to the same skool file:

    $ skool2bin.py -E 65536 wrap.skool
    $ skool2ctl.py wrap.skool > wrap.ctl
    $ sna2skool.py -I Wrap=1 wrap.bin

**Comment by Wolfe-Lyon** [comment]
That works well, thanks.

I have since discovered...

### Issue 3
When using `@rfix` mode in `skool2bin.py` (etc.) to remove one or more bytes, everything above the removed byte(s) gets relocated down, including the `JR` instruction which has to remain at address 65535 for the interrupt routine to work correctly.

Is there a way of marking certain addresses so that SkoolKit does not try to relocate the contents of those addresses in `@rfix` (etc.) mode?

**Comment by skoolkid** [comment]
Yes, the simplest way to prevent an instruction from moving is to stick an `@org` directive on it. For example:

```
; Routine at 65500 followed by a gap
c65500 RET

@org
; Fixed at 65535
c65535 RET
```

If you run `skool2bin.py` on this skool file, you'll get a 36-byte binary file with RET at each end.

**Comment by Wolfe-Lyon** [comment]
Thanks, that works. 283 `@ssub` directives later, I have a version of Spellbound with significantly fewer bugs!
