### ISSUE TITLE
Multi-instruction comment that spans more than one instruction type is not preserved

### ISSUE THREAD

**Issue by Wolfe-Lyon** [skoolkid/skoolkit#117]
SkoolKit 8.4

Consider this skool file:

```
; Data block at 40847
b40847 DEFB 249,2,1     ; {Comment
 40850 DEFB 3,3         ;
 40852 DEFW 40858       ; }
```

When this is run through skool2ctl then sna2skool, the result is:

```
; Data block at 40847
b40847 DEFB 249,2,1
 40850 DEFB 3,3
 40852 DEFW 40858
```

The multi-instruction comment has been lost. It is still present in the ctl file, however:

```
b 40847 Data block at 40847
M 40847 Comment
B 40847,5,3,2
W 40852,2,2
i 40854
```

**Comment by skoolkid** [comment]
Thanks for reporting this bug. Looks like it's been around since 7.2.

Anyway, it should be fixed now by 37202f508e40b58e68c05bb29891804a1d8ae59c.
