### ISSUE TITLE
PEEK Macro is giving an unexpected value

### ISSUE THREAD

**Issue by Rui1973Martins** [skoolkid/skoolkit#121]
Given the following macro definition:
```
 #DEF(#COLORNAME(color)  #MAP($color)(UNKNOWN,0:BLACK,1:BLUE,2:RED,3:MAGENTA,4:GREEN,5:CYAN,6:YELLOW,7:WHITE))
```
The following code and comments
```
 $981A CP $04        ; {
 $981C JR NC,$9820   ; inkColor = ( borderColor is >= #COLORNAME($04) ) ? WHITE : BLACK
 $981E LD B,$07      ; }
```

Results in this description
> inkColor = ( borderColor is >= GREEN ) ? WHITE : BLACK

Which is fine, correct and expected.

However, if we use PEEK with the location of the CP parameter ($981B):
```
 $981A CP $04        ; {
 $981C JR NC,$9820   ; inkColor = ( borderColor is >= #COLORNAME(#PEEK$981B) ) ? WHITE : BLACK
 $981E LD B,$07      ; }
```

The results is unexpectedly BLACK

> inkColor = ( borderColor is >= BLACK ) ? WHITE : BLACK

Am I doing anything wrong ?

**Comment by Rui1973Martins** [comment]
NOTE:
If I change the expression to `inkColor = ( borderColor is >= #COLORNAME($04) ) ? WHITE : BLACK :> #PEEK$981B`

I get:

> inkColor = ( borderColor is >= GREEN ) ? WHITE : BLACK :> 0

Then I see that the problem is in the PEEK Macro itself.
Or some memory has been overwritten during processing.

**Comment by pobtastic** [comment]
`$981C JR NC,$9820   ; inkColor = ( borderColor is >= #COLORNAME(#PEEK($981B))) ? WHITE : BLACK`

**Comment by skoolkid** [comment]
You are probably missing an [@assemble](https://skoolkit.ca/docs/skoolkit/asm.html#assemble) directive, to make sure that assembly language instructions are converted into byte values.

**Comment by Rui1973Martins** [comment]
I tried the change to see if that was the cause `inkColor = ( borderColor is >= #COLORNAME($04) ) ? WHITE : BLACK :> #PEEK($981B)`

But it doesn't solve the issue, since I get the same wrong result (0), instead of 4:
> inkColor = ( borderColor is >= GREEN ) ? WHITE : BLACK :> 0

**Comment by Rui1973Martins** [comment]
Regarding the @assemble directive, it doesn't seem to apply, since this byte is part of an actual instruction and not a `DEFB` or `DEFW`.

**Comment by skoolkid** [comment]
Did the `@assemble` directive fix the problem?

By the way, the fact that assembly language instructions are not converted into byte values by default is by design. `@assemble` was introduced in 5.0, and if `@assemble=2` were the default, that would have negatively affected the performance of skool2html.py compared to 4.x.

I'll add a note to the documentation on the `#PEEK` macro about using `@assemble` to ensure that assembly language instructions are converted into byte values.

**Comment by Rui1973Martins** [comment]
I think I understand the issue.
There is some other representation of the actual data, being used instead of the original snapshot memory dump.

But shouldn't PEEK  just have access to the original snapshot memory dump and just fetch the byte directly ?
What prevents this ?

**Comment by skoolkid** [comment]
> But shouldn't PEEK just have access to the original snapshot memory dump and just fetch the byte directly ? What prevents this ?

No, `#PEEK` does not have access to the original snapshot. The skool file has no knowledge of any snapshot.

> I have not tried the @assemble yet. And I would prefer not to pollute the disassembly, with extra stuff to work around feature behaviours, if I can avoid it.

The best way to make `#PEEK` work in this case is to place an `@assemble=2` directive in the skool file, at some point before the instruction whose byte values you want to inspect.

**Comment by Rui1973Martins** [comment]
> No, #PEEK does not have access to the original snapshot. The skool file has no knowledge of any snapshot.

Ah!

We are getting back to the ideia I mentioned the other day, that the Skool file should be like a project file and have references to CTL and snapshot file, defined somewhere.

Ok, Thank you for all the info and feedback.

**Comment by skoolkid** [comment]
I've updated the documentation on the [#PEEK](https://skoolkit.readthedocs.io/en/latest/skool-macros.html#peek) macro. It now mentions the `@assemble` directive.
