### ISSUE TITLE
Add a --dump-binary option to snapinfo.py

### ISSUE THREAD

**Issue by programadorhedonista** [skoolkid/skoolkit#122]
**Enhancement request**

Add a --dump-binary option to snapinfo.py

  _--dump-binary start,end,filename.bin_

Somewhat similar to _--peek A[-B[-C]]_

**Comment by skoolkid** [comment]
I'll consider this for SkoolKit 8.8.

In the meantime, something like this would do the job in most cases:

    sna2skool.py -s start -e end game.z80 | skool2bin.py - file.bin

And if it doesn't, this should:

    echo -e 'b start\ni end' | sna2skool.py -c - game.z80 | skool2bin.py - file.bin

**Comment by skoolkid** [comment]
Actually, I think the *-d/--defb* option of sna2skool.py (new in 8.7) makes a *--dump-binary* option unnecessary:

    sna2skool.py -d 1 -s start -e end game.z80 | skool2bin.py - file.bin

That should always work (and is simpler than the `echo -e 'b start\ni end'` technique).
