### ISSUE TITLE
Info: Archlinux support

### ISSUE THREAD

**Issue by vschwaberow** [skoolkid/skoolkit#123]
Just wanted to inform you that I added an AUR package to Archlinux which supports the skoolkit base package

https://aur.archlinux.org/packages/skoolkit

**Comment by skoolkid** [comment]
Funnily enough, I came across that page yesterday. Thanks! To my knowledge, you're the first person to package SkoolKit for a Linux distribution other than me. (I used to create packages for Fedora and Ubuntu, but stopped doing that a couple of releases ago.)
