### ISSUE TITLE
Any way to avoid repeating a mid-block comment in a loop

### ISSUE THREAD

**Issue by pobtastic** [skoolkid/skoolkit#124]
I've probably phrased that badly ... So here's an example instead:

I have a bunch of these blocks, but I want the comment to appear above the loop block instead of after every loop.

```
N $6376 Background Table #N$07.
W $6376,$02 Background graphic #R(#PEEK(#PC) + #PEEK(#PC + $01) * $100).
B $6378,$02 X/ Y position = #N(#EVAL(#PEEK(#PC) / $08)) / #N(#EVAL(#PEEK(#PC + $01) / $08)).
L $6376,$04,$16
  $63CE,$02 Terminator.
```

At the moment, I work around it by just removing the first "block" and repeating from the second one:

```
N $6376 Background Table #N$07.
W $6376,$02 Background graphic #R(#PEEK(#PC) + #PEEK(#PC + $01) * $100).
B $6378,$02 X/ Y position = #N(#EVAL(#PEEK(#PC) / $08)) / #N(#EVAL(#PEEK(#PC + $01) / $08)).
W $637A,$02 Background graphic #R(#PEEK(#PC) + #PEEK(#PC + $01) * $100).
B $637C,$02 X/ Y position = #N(#EVAL(#PEEK(#PC) / $08)) / #N(#EVAL(#PEEK(#PC + $01) / $08)).
L $637A,$04,$15
  $63CE,$02 Terminator.
```

It's not a big deal at all, and potentially even - these shouldn't even be in just one sub-block (it's huge), so TBH - I might even change my mind later and make it a `w` rather than an `N` but I do tend to run into this fairly often, which is more to do with my style of disassembling than anything (i.e. I can change what I do if there's a nicer way to do it).

**Comment by pobtastic** [comment]
I kind of want to add a header and a footer 😂

**Comment by skoolkid** [comment]
No, there's currently no way to avoid repeating 'N' directives in a control file loop. However, I can see the value in it and I think it should be easy to add support for it, so watch this space.

**Comment by pobtastic** [comment]
Hiya!  Wonderful!!!  Thank you so much 😄

**Comment by skoolkid** [comment]
I've added support for avoiding repetition of an 'N' directive at the start of a loop: 183146f6d2df25f0d2166ecc43e41978c2f0d696.

See [here](https://skoolkit.readthedocs.io/en/latest/control-files.html#ctlloops) for documentation. (In short, do: `L $6376,$04,$16,2`.)

Let me know if it works as you expect/need/want!

**Comment by pobtastic** [comment]
That is _PERFECT_!!!  Thank you so much!
