### ISSUE TITLE
skool2asm warnings with addresses in Screen Memory

### ISSUE THREAD

**Issue by mrcook** [skoolkid/skoolkit#126]
Hi Richard,

When converting a skool file containing `LD HL,$5900` with `skool2asm.py` I get the following warning:
```
WARNING: No label for address ($5900):
```

It seems unnecessary to throw a warning for Screen Memory addresses, or possibly for any address below 0x5B00.

**Comment by skoolkid** [comment]
Hi Michael

I don't think screen memory should be treated differently from memory anywhere else in this regard. In any case, if you want to suppress the warning for that particular instruction, you could attach either a [@keep](https://skoolkid.github.io/skoolkit/asm.html#keep) or a [@nowarn](https://skoolkid.github.io/skoolkit/asm.html#nowarn) directive to it.

**Comment by mrcook** [comment]
Thanks, I'll use one of those then.
