### ISSUE TITLE
Setting shadow registers via -r/--reg in bin2sna.py is badly broken.

### ISSUE THREAD

**Issue by sjbaines** [skoolkid/skoolkit#127]
Docs say that ^ prefix in -r/--reg specifies shadow registers, but in practice any such prefix is silently ignored.
This means that attempts to set the shadow registers actually set the main registers instead (ouch).
e.g. `bin2sna.py -r bc=0x1234 -r ^bc=0x5678`
should set BC to 0x1234 and BC' to 0x5678, but actually sets BC to 0x5678, and leaves BC' uninitialised.

FYI, as a temporary local workaround, I made changes to skoolkit/snapshot.py to use _ instead of ^ as the prefix.
I replaced `if reg.startswith('^') `with `if reg.startswith('_')` in `set_z80_registers`, and in the register definitions in `Z80_REGISTERS` similarly replaced ^ with _.
This then worked for me, but is only a workaround.

**Comment by skoolkid** [comment]
The ^ prefix works for me. Are you using Windows, by any chance? It might be that whatever shell you're using treats ^ as an escape character. Try doubling it and see if that works:

    bin2sna.py -r ^^bc=0x5678 ...

**Comment by sjbaines** [comment]
Thanks, you are correct. I am using standard Windows command shell.
Confirmed that using ^^ prefix instead of ^ is giving correct behaviour.
