### ISSUE TITLE
Change of html output path breaks bases.ref/bases.py

### ISSUE THREAD

**Issue by AtricoSoftware** [skoolkid/skoolkit#129]
Skoolkit 9.1
Trying to use bases.ref, bases.py to create hex and dec html with link
Using command given in docs:

python skool2html.py -D -d html/dec -c Config/InitModule=:bases Game.skool bases.ref
python skool2html.py -H -d html/hex -c Config/InitModule=:bases Game.skool bases.ref

This creates sites at

html/dec/Game
html/hex/Game

However, bases.py seems to ignore the last part of this path (/Game) and this creates the "switch to decimal/hex" link (skoolkit['AltPath']) as

html/dec/hex
html/hex/dec

~~From a quick look at the code in bases.py it is not obvious how to fix this~~

**Comment by AtricoSoftware** [comment]
Looking again at the code, the fix is actually easy
PR raised

**Comment by skoolkid** [comment]
Hi @AtricoSoftware

`bases.py` is just sample code designed to work with the very specific example given in the documentation. The change in your PR would break that example!

Of course you can still modify `bases.py` as needed to work for your own particular project.

**Comment by pobtastic** [comment]
You know ... there may well be _something_ up with how bases.py works.  Of course, it could just be with how I'm implementing it, but I've had two people now tell me that they have issues with the initial build:

https://github.com/pobtastic/westbank/issues/2

Once they comment (or whatever) "Path" - then the next build it's fine.  I've never looked into it myself, as it doesn't seem to occur for me.

**Comment by skoolkid** [comment]
Just to be sure, I tried using `bases.py` and `bases.ref` as described in the documentation, and they work as expected.

They will *not* work if you use `-d DIR` instead of `-c Config/GameDir=DIR` to specify an output directory. That is also expected.

**Comment by AtricoSoftware** [comment]
OK, Tried again (without -d) and it works fine!
PR removed
