### ISSUE TITLE
SCR Maybe Frames Issue?

### ISSUE THREAD

**Issue by pobtastic** [skoolkid/skoolkit#131]
Maybe I'm just doing this wrong, or perhaps this just isn't what `#SCR` is for ...

So, I thought I'd try my hand at "capturing" the Booty intro screen animation.  Usually, I'd do it in Python, but with the new `#SIM` stuff (which is AMAZING by the way!) I'd assumed the following would work:

```
c $CD86 Display Introduction Screen
@ $CD86 label=DisplayIntroductionScreen
D $CD86 #PUSHS #SIM(start=$CD93,stop=$CDA8) #FOR$01,$08(x,#SIM(start=$D0AC,stop=$D0D3)#SCR$02(*title-screen-x)) #POPS
. #UDGARRAY*title-screen-1,15;title-screen-2;title-screen-3;title-screen-4;title-screen-5;title-screen-6;title-screen-7;title-screen-8(title-screen-animated)
```

But, it only gives me a (seemingly) static image of the loading screen (because this exists at $4000 as you'd expect).  I'd assumed that probably only `#UDGARRAY` supports it ...

However ...  Changing to `#SCR$02(title-screen-x*)` I can see that all the images were created just fine, and do appear to contain the (sort of) animation.

<img width="1283" alt="Screenshot 2024-03-25 at 09 53 17" src="https://github.com/skoolkid/skoolkit/assets/1250035/a8755e78-6ae0-4790-bbdb-beea97602a0d">

Should this work, or should I be using `#UDGARRAY` and accept that this is a crazy idea anyway?

**Comment by skoolkid** [comment]
This should definitely work, but I know why it doesn't: to improve performance, a frame's UDGs are evaluated lazily (i.e. at the time they're converted into an image, which may be well after the frame itself is created). So because all your frames are based on graphic data at the same address ($4000), *and* you're using #PUSH/#POPS on top of that, the frames are hopelessly stale by the time the #UDGARRAY* macro is expanded.

I'll fix this for SkoolKit 9.2.

In the meantime, you could use the following (cumbersome and slower) workaround that's unaffected by the lazy evaluation bug:

    #PUSHS #SIM(start=$CD93,stop=$CDA8) #FOR$01,$08($n,#SIM(start=$D0AC,stop=$D0D3) #UDGS(32,24)(*ts-$n)(#LET(df=$4000+2048*($y/8)+32*($y%8)+$x) #LET(af=$5800+32*$y+$x) #UDG({df},#PEEK({af}),2,256)(*udg) udg)) #POPS
    #UDGARRAY*ts-1,15;ts-2;ts-3;ts-4;ts-5;ts-6;ts-7;ts-8(ts-animated)

**Comment by skoolkid** [comment]
If you find that workaround repugnant, you could try this hack that uses a no-op #PLOT macro to force the #SCR frames to be evaluated early:

    #PUSHS #SIM(start=$CD93,stop=$CDA8) #FOR$01,$08(x,#SIM(start=$D0AC,stop=$D0D3)#SCR$02(*title-screen-x)#PLOT(0,0,0)(title-screen-x)) #POPS

**Comment by pobtastic** [comment]
Ha!  That PLOT trick is nice!!! :D It works a treat, thank you so much!

Not sure if github will know what to do with an animated png ...

![image](https://github.com/skoolkid/skoolkit/assets/1250035/bff7d695-50a2-47b6-8e86-caa53925d022)

**Comment by pobtastic** [comment]
Closing; as just wanted to bring this to your attention.

**Comment by pobtastic** [comment]
Just for reference, and to make this searchable in github ... I ended up doing this in the control file:
```
> $4000 @expand=#DEF(#ANIMATE(delay,count=$50)(name=$a)*$name-1,$delay;#FOR$02,$count||x|$name-x|;||($name-animation))

...

c $CD86 Display Introduction Screen
@ $CD86 label=DisplayIntroductionScreen
N $CD86 #PUSHS #UDGTABLE {
.   #SIM(start=$CD93,stop=$CDA8) #FOR$01,$08(x,#SIM(start=$D0AC,stop=$D0D3)#SCR$02(*title-screen-x)#PLOT(0,0,0)(title-screen-x))
.   #UDGARRAY#(#ANIMATE$0F,$08(title-screen))
. } UDGTABLE# #POPS

...

c $CE41 Hidden Goldfish Game
@ $CE41 label=GoldfishGame
D $CE41 See #POKE#goldfishGameAccess(Access Hidden Game).
N $CE41 #PUSHS #UDGTABLE {
.   #SIM(start=$CD63,stop=$CD6C)#SIM(start=$CE61,stop=$CF21)
.   #FOR$01,$50(x,#SIM(start=$CF44,stop=$CF4E)#SIM(start=$CF73,stop=$CF76)
.     #SCR$02(*goldfish-gameplay-x)#PLOT(0,0,0)(goldfish-gameplay-x)
.   )
.   #UDGARRAY#(#ANIMATE$0F(goldfish-gameplay))
. } UDGTABLE# #POPS

...

c $D8A2 Goldfish Game: Animate Boats
@ $D8A2 label=GoldfishGame_AnimateBoats
N $D8A2 #PUSHS #UDGTABLE {
.   #SIM(start=$CD63,stop=$CD6C)#SIM(start=$CE61,stop=$CF0B)
.   #FOR$01,$50||x|#SIM(start=$CF47,stop=$CF4E)#SIM(start=$CF73,stop=$CF76)
.     #SCR$02,$00,$00,$20,$09(*boats-x)#PLOT(0,0,0)(boats-x)
.   ||
.   #UDGARRAY#(#ANIMATE$0F(boats))
. } UDGTABLE# #POPS

...

c $D8E2 Goldfish Game: Animate Sand
@ $D8E2 label=GoldfishGame_AnimateSand
N $D8E2 #PUSHS #UDGTABLE {
.   #SIM(start=$CD63,stop=$CD6C)#SIM(start=$CE61,stop=$CF08)
.   #FOR$01,$50||x|#SIM(start=$D8E2,stop=$D929)
.     #SCR$02,$00,$13,$20,$03(*sand-x)#PLOT(0,0,0)(sand-x)
.   ||
.   #UDGARRAY#(#ANIMATE$0F(sand))
. } UDGTABLE# #POPS
```

I might still tweak it here and there, but I'm very happy with how it came out:
https://pobtastic.github.io/booty/asm/CD86.html
https://pobtastic.github.io/booty/asm/CE41.html
https://pobtastic.github.io/booty/asm/D8A2.html
https://pobtastic.github.io/booty/asm/D8E2.html

(Obviously, the disassembly is still in progress... but I feel like this one won't cause me headaches like Rampage did).
