### ISSUE TITLE
#SIM Output Inconsistent With Game

### ISSUE THREAD

**Issue by pobtastic** [skoolkid/skoolkit#132]
Maybe this is just me doing it wrong, but I have used `#SIM` quite successfully a number of times already - and I find it quite ... nice (!) to include little images of even the "admin" screens.  This is the first time that I've encountered anything like this.

This is the code (Booty):

```
c $D188 Set User-Defined Keys
@ $D188 label=SetUserDefinedKeys
N $D188 #PUSHS #UDGTABLE {
.   #SIM(start=$CDD1,stop=$CDE9)
.   #SIM(start=$CD6F,stop=$CD85)
.   #SIM(start=$D188,stop=$D19D)
.   #SIM(start=$D1A6,stop=$D1BF)
.   #SCR$02(user-defined-keys)
. } UDGTABLE# #POPS
```

https://pobtastic.github.io/booty/asm/CDD1.html
Clears the screen and sets a heading from the title screen (which is reused on the next screen).

https://pobtastic.github.io/booty/asm/CD6F.html
Sets default values for the user-defined keys.

https://pobtastic.github.io/booty/asm/D188.html
The "set user-defined keys" routine.  Clears the screen below the heading, prints "DEFINE KEYS"...

https://pobtastic.github.io/booty/asm/D188.html#d1a6
I've skipped over a small "pause" loop for debouncing, but then it prints the keys from a keymap at https://pobtastic.github.io/booty/asm/D22C.html.

So the odd thing is; all of this is correct until the last two keys.  They should be:

<img width="635" alt="Emulator" src="https://github.com/skoolkid/skoolkit/assets/1250035/866a7e0b-6dd1-4be8-8262-1621ed38d4cc">

But in the disassembly, I see it as:

![image](https://github.com/skoolkid/skoolkit/assets/1250035/31c6b707-f1e8-41e0-a88e-7bbd7b2dba6a)

I've tried various things already, like:
* POKE-ing values directly to the user-defined keys table
* Adding `cmio=1` to that last `#SIM`
* Some of the other `#SIM`s need to write 0x00 to [DF_SZ](https://skoolkit.ca/disassemblies/rom/hex/asm/5C6B.html) but it obviously has no impact for this

I'm pretty stumped now, so thought I'd reach out.

**Comment by skoolkid** [comment]
Just had a look at this and found that the stack (which #SIM defaults to $5C00) is overwriting the user-defined keys table at $5BEB (specifically, the byte at $5BEE), which messes up what's printed by the routine at $D20D.

Simplest fix is to change the `#SIM(start=$CDD1,stop=$CDE9)` to `#SIM(start=$CDD1,stop=$CDE9,sp=$68DD)`, $68DD being where the stack actually is when the game is running.

But perhaps best of all is to have the very first #SIM macro in the skool file be `#SIM(sp=$68DD)`, to make sure that all the subsequent #SIM macros operate with the stack in a safe place.
