### ISSUE TITLE
#FONT Spacing

### ISSUE THREAD

**Issue by pobtastic** [skoolkid/skoolkit#135]
Hiya!

It's a minor thing, but a lot of my disassemblies are made just to get an outline so I can take the graphics and reimplement the games in other languages (a lot are on [Fuze](https://fuzearena.com/) on the Switch for anyone interested!)

Generally, this issue doesn't matter ... as I tend to implement the same kind of "print character" routine across all my games, which just pulls from the font UDGs (which is why this is minor), but I noticed this morning that #FONT seems to truncate intentional whitespace.

Check this out:
![header](https://github.com/user-attachments/assets/450b672f-4355-4239-bf01-d84c56423979)

And the code is:
```
t $8C48 Messaging: Header
@ $8C48 label=Messaging_Header
  $8C48,$1E,$1D:$01 #FONT:(Score  Trashman           Cash)$F840,attr=$4E(header)
```

What's so interesting about this, is that it retains the double spacing between "Score" and "Trashman", but not the spacing afterwards.

**Comment by pobtastic** [comment]
An only-semi-related question too ... is it possible to "auto-" get the string for the input in any way?  I'm assuming not, as I think I've tried many different ways over the years - but it always prints the raw input instead.

It's maybe a little much to expect it to function similarly to `#STR` - but I wondered if there was any way perhaps to make it function like say, `#FORMAT` does.

Again, this is incredibly minor - as for the most part, for things like this, I tend to write a script to auto-generate lines like these anyway.

**Comment by skoolkid** [comment]
I suspect what's happening here is that the spacing between 'Trashman' and 'Cash' is lost when the line containing the `#FONT` macro is wrapped in the skool file.

Two possible workarounds spring to mind: set a variable (using `#LET`) to the desired message in a line that won't wrap, or use a `#STR` macro as an argument to the `#FONT` macro. This skool file snippet illustrates both approaches:

```
@rom
@expand=#LET(msg$=Score  Trashman           Cash)
; Message
;
; #FONT#(:(#STR32768))$3D00
; .
; #FONT#(:(#FORMAT({msg$})))$3D00
t32768 DEFM "Score  Trashman           Cash",0
```

The trick here is to use the `#()` macro to expand `#STR` or `#FORMAT` before `#FONT` sees it.

Let me know if either of these works for you.

**Comment by pobtastic** [comment]
Wonderful!!!  That works a treat!  As always, thank you for everything!

This works great:
```
$8C48,$1E,$1D:$01 #FONT#(:(#STR(#PC)))$F840,attr=$4E(header)
```
