### ISSUE TITLE
Macro Suggestion - #PLURAL?

### ISSUE THREAD

**Issue by pobtastic** [skoolkid/skoolkit#137]
Hiya!

I was wondering if this already exists in some form, but if it doesn't, perhaps it'd be good to implement some kind of `#PLURAL` macro.

It's a real minor point, and obviously it could just be fulfilled with a simple `#IF` - but I wondered if it's a nice helper macro?  Something like;

`#PLURAL(count,single_string,pluralised_string)`

```
@expand=#DEF(#PLURAL(count)(s=$s,p=$p) #IF($count==$01)($s,$p))
```

```
g $D879 Initialised Game Defaults
@ $D879 label=Defaults
D $D879 Used by the routine at #R$D2A1.
B $D879,$02 #LET(count=#PEEK(#PC)) Repeat #N(#PEEK(#PC+$01)) x #N({count}) #PLURAL({count})(time,times).
L $D879,$02,$07
B $D887,$01 Terminator.
B $D888,$06
```

But ... what'd be better would be if I could do something more like this: (I appreciate it's a bad example)

`B $D879,$02 #PLURAL(#PEEK(#PC))(Repeat #N(#PEEK(#PC+$01)) just one time,Repeat #N(#PEEK(#PC+$01)) x {count} times).`

```
@expand=#DEF(#PLURAL(count)(s=$s,p=$p) #LET(count=$count)#FORMAT(#IF($count==$01)($s,$p)))
```

Which would then output:
```
  | D879 | DEFB $04,$04 | Repeat 04 x 4 times.
  | D87B | DEFB $06,$02 | Repeat 02 x 6 times.
  | D87D | DEFB $02,$01 | Repeat 01 x 2 times.
  | D87F | DEFB $01,$09 | Repeat 09 just one time.
  | D881 | DEFB $0D,$00 | Repeat 00 x 13 times.
  | D883 | DEFB $04,$03 | Repeat 03 x 4 times.
  | D885 | DEFB $04,$06 | Repeat 06 x 4 times.
  | D887 | DEFB $FF | Terminator.
```

This is fine and all, but if I change it to "Repeat #N(#PEEK(#PC+$01)) x #N{count} times" then I get a parsing error (due to `#N` not "seeing" the parameters) - it has to be `#N({count})` ... but regardless, it's easier to implement in python.

**Comment by pobtastic** [comment]
Hmmmm you're right, maybe it is niche 👍  It's all good, I just tend to work with various CMS applications and it's something we use a lot there.  Maybe it's just more geared towards the way that I tend to work than how other people might need to make their commenting dynamic.

And yeah, what I have already works for me - was just wondering how useful it might be to a wider audience 👍

**Comment by mooskagh** [comment]
also note that it's English-specific, other languages have different rules for using plural forms -- although arguably all ZX Spectrum game reverse engineering happens in English anyway.

**Comment by pobtastic** [comment]
Yeah, that was the thinking with this one being better:

`B $D879,$02 #PLURAL(#PEEK(#PC))(Repeat #N(#PEEK(#PC+$01)) just one time,Repeat #N(#PEEK(#PC+$01)) x {count} times).`

As the ordering of the wording can then be changed (as you say, as it might be in other languages).
