### ISSUE TITLE
@rfix mode example uses @rsub

### ISSUE THREAD

**Issue by dpt** [skoolkid/skoolkit#93]
http://skoolkit.ca/docs/skoolkit/asm.html#rsubmode

The `@rfix` mode example shows `@rsub` in use not `@rfix`.

**Comment by skoolkid** [comment]
Wow, this mistake was introduced back in SkoolKit 2.3 (October 2011):

http://skoolkit.ca/docs/skoolkit-2.3/asm.html#rfix-mode

Well spotted!

**Comment by skoolkid** [comment]
Fixed in cfab303f4520bdfac8f50ecba0c54d61be35e593.
