### ISSUE TITLE
Misplaced zero byte via skool2bin

### ISSUE THREAD

**Issue by dpt** [skoolkid/skoolkit#96]
I've got two routes to build an emulator image in the current The Great Escape build:

  1. .skool -> skool2asm -> .asm -> pasmo -> .bin -> bin2tap = .tap  ("make tap")
  2. .skool -> skool2bin -> .bin -> bin2sna = .z80  ("make z80")

I've just diffed the two built .bins while diagnosing a crashing snapshot and spotted a difference in the skool2bin case which doesn't look correct.

This chunk:

```
@label=searchlight_movements
w$AD29 DEFB $24, $52, $2C, $02, $00 ; x, y, step, direction, counter
 $AD2D DEFW $AD54   ; searchlight_path_2
 $AD2F DEFB $78, $52, $18, $01, $00 ; x, y, step, direction, counter
 $AD34 DEFW $AD43   ; searchlight_path_1
 $AD37 DEFB $3C, $4C, $20, $02, $00 ; x, y, step, direction, counter
 $AD3C DEFW $AD3E   ; searchlight_path_0
```

Should emerge as:

`24 52 2c 02 00 54 ad 78 52 18 01 00 43 ad 3c 4c 20 02 00 3e ad`

and in the Pasmo case it's correct:

```
0006d20: 24 3a 6a ab 77 e1 f1 c1 c9 24 52 2c 02 00 54 ad  $:j.w....$R,..T.
0006d30: 78 52 18 01 00 43 ad 3c 4c 20 02 00 3e ad 20 02  xR...C.<L ..>. .
```

but in the skool2bin case I see:

```
0006d20: 24 3a 6a ab 77 e1 f1 c1 c9 24 52 2c 02 54 ad 78  $:j.w....$R,.T.x
0006d30: 52 18 01 00 43 ad 00 3c 4c 20 02 00 3e ad 20 02  R...C..<L ..>. .
```

The zero which ought to be at $6D2D appears to be at $6D36.

Am I doing something daft and failing to spot it?

**Comment by skoolkid** [comment]
I think the problem is that the addresses in the skool file snippet don't match up with the lengths of the DEFB and DEFW statements. Shouldn't it read like this instead?

    w$AD29 DEFB $24, $52, $2C, $02, $00 ; x, y, step, direction, counter
     $AD2E DEFW $AD54   ; searchlight_path_2
     $AD30 DEFB $78, $52, $18, $01, $00 ; x, y, step, direction, counter
     $AD35 DEFW $AD43   ; searchlight_path_1
     $AD37 DEFB $3C, $4C, $20, $02, $00 ; x, y, step, direction, counter
     $AD3C DEFW $AD3E   ; searchlight_path_0

**Comment by dpt** [comment]
Something daft it was. Thanks, and sorry to bother!
