### ISSUE TITLE
Text in DEFM containing number gets replaced by label that equals that number

### ISSUE THREAD

**Issue by TheJare** [skoolkid/skoolkit#97]
I am still in the phase where I am generating an .asm from a skool and a control file, with command line:

`python skoolkit-6.0\skool2asm.py s1.skool > s1.asm`

I have manually labelled a function `DrawStarfield` via the control file. One of the labels generated by skool2asm during this process, DrawStarfield_06, inside that function, ends up referring to memory address 50000 (decimal).

Later on in the skool file, there is a DEFM text field that contains text like:

`$E0B3 DEFM "MARIA   050000"`

In the generated ASM file, this becomes

`  DEFM "MARIA   DrawStarfield_06"`

Which destroys the text and the entire memory layout of the remainder of the generated file. Note that it is replacing the entire `050000` substring **including** the leading zero.

**Comment by skoolkid** [comment]
Thanks for reporting this! I'll fix it for 6.1.

In the meantime, as a workaround you could split the DEFM statement into pieces. For example:

    DEFM "MARIA 05","0000"

**Comment by TheJare** [comment]
I can't split the DEFM directly since I am still generating the skool file from a snapshot + ctl, so I just added a 't' directive in the middle of the string, to generate an entirely new DEFM section and workaround the bug. Cleaner that my previos workaround, thanks!

**Comment by skoolkid** [comment]
You can split the DEFM statement in the control file too. Try this:

   T $E0B3,12,8:4

**Comment by skoolkid** [comment]
Fixed in f4143fcdab510c3d4033b94fcba0a1706ee4cea6.
