### ISSUE TITLE
EQU lines are indented like instructions

### ISSUE THREAD

**Issue by TheJare** [skoolkid/skoolkit#98]
Hi!

There seems to be a mismatch between the EQU directives emitted by skool2asm and how sjasmplus expects them. skool2asm emits them indented like instructions, but sjasmplus expects them unindented, because the symbol is a label and labels must always appear unindented. My vague memory of how most assemblers work matches with what I see sjasmplus expecting, and while I have not tried pasmo, the docs also match this explanation.

**Comment by skoolkid** [comment]
I've only tested the EQU directives produced by skool2asm.py with pasmo, but if unindented EQU directives work with both sjasmplus and pasmo, I'll remove the indent.

**Comment by skoolkid** [comment]
Indent removed in fead013b3d3113307a974ea6a9a1a38ec22b06f4.
